name: Deploy to Surge.sh
on: [push]
jobs:
    build-and-deploy:
        concurrency: ci-${{ github.ref }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v3

            - name: Build 🔧
              run: |
                  npm run build

            - name: Deploy 🚀
              uses: YieldRay/deploy-to-surge-action@v1
              with:
                  folder: .
                  domain: aoqilegend.surge.sh
                  token: ${{ secrets.SURGE_TOKEN }}